### ISSUE TITLE
US 02.05.01: As a meal planner, I want to edit the details of a recipe, including the ingredients.

### ISSUE THREAD

**Issue by JulianCamiloGallego** [CMPUT301F22T04/nosh#12]
**Preconditions**

- User has a list of recipes
- The user is given the option to edit a recipe (tap on list item)

**Acceptance Criteria**

- Upon taping on a recipe the user is taken to a page were he can edit the detailed of the selected item
- This page should be the same as the view recipe page
- This page should handle both the viewing and editing of an recipe's details.

**Comment by Dekr0** [comment]
should a user able to change information of an ingredient during editing the detail of a recipe?

**Comment by JulianCamiloGallego** [comment]
Yes, we will have to include an extra dialog for selected ingredients.
