### ISSUE TITLE
Project Part-02 Scores

### ISSUE THREAD

**Issue by AbdulAli** [CMPUT301F22T04/nosh#43]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/abdulalib/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/abdulalib/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

score   (/3) | comment | score   (/3) | comment | score   (/3) | comment | score   (/3) | comment | Final   comments
-- | -- | -- | -- | -- | -- | -- | -- | --
Tool Practices | Product   Backlog | Object-Oriented   Analysis | User   Interface Mockup and Storyboard | Other
3 | Excellent   but it seems like only one person made all the story boards. This is   unacceptable. October 11, 2022 Meeting Minutes are unreadable. start using   branches for each issue. | 3 | ✓   Numbered, tracked, and organized requirements     ✓Comprehensive requirements     ✓ Complete story point estimates     ✓ Complete risk levels     ✓ Displays understanding of requirements specification/elicitation     ✓ Requirements noted for half-way checkpoint | 3 | •   Clear, readable, consistent, and organized: Yes     • Covers key classes: Yes     • Complete responsibilities: Yes     • Complete collaborators: Yes     • Object-oriented: Yes. However, I have some concerns regarding the Meal   class.     • Cohesive classes: Yes     • Coupling managed: Yes | 3 | Fix   the meal plan screen with realistic data.

</body>

</html>

**Comment by AbdulAli** [comment]
Hi guys @Hishamanik  @Dekr0  @JulianCamiloGallego  @Isaac415   
Please tag the other team members as i cant seem to find them on the tagging list.
Please create a separate issue to address each feedback, thanks.

**Comment by Hishamanik** [comment]
@m-powar @FNov10

**Comment by Hishamanik** [comment]
> Hi guys @Hishamanik @Dekr0 @JulianCamiloGallego @Isaac415 Please tag the other team members as i cant seem to find them on the tagging list. Please create a separate issue to address each feedback, thanks.

@m-powar @FNov10
