### ISSUE TITLE
US 02.02.01: As a meal planner, I want to add an ingredient to a recipe, with a brief description, amount, unit, and ingredient category.

### ISSUE THREAD

**Issue by JulianCamiloGallego** [CMPUT301F22T04/nosh#9]
**Preconditions**

- The is a list of recipes
- The user is given the option to add an ingredient to a recipe

**Acceptance Criteria**

- The user should be shown a dialog pop up where he can add an ingredient with the above fields to a recipe
- This should apply to both the add page and edit/view page
- While some of the fields above could remain empty, an ingredient should always have a name.

**Comment by Dekr0** [comment]
Should an ingredient exists before adding it into a recipe?

**Comment by Dekr0** [comment]
Should an ingredient exists before adding it into a recipe?

**Comment by JulianCamiloGallego** [comment]
No, if I understand correctly the ingredient storage is separate from a recipe's ingredients. A user will add ingredients to recipes and the shopping list will be derived from the missing ingredients not in the storage required to complete the recipes. It might be good to add the option to select from ingredients already in the storage though.
